import React from 'react'

const TextMain = () => {
    return (
       <div>
          <h2 className="text-left ml-20 mt-9 mb-4 font-serif text-xl text-pink-800 font-bold">Flower viewing in Japan</h2>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">"Hanami" is the centuries-old practice of drinking under a blooming sakura or ume tree. The custom is said to have started during the Nara period (710–794), when it was ume blossoms that people admired in the beginning, but by the Heian period (794–1185) cherry blossoms came to attract more attention, and hanami was synonymous with sakura.[8] From then on, in both waka and haiku, "flowers" (花, hana) meant "cherry blossoms". The custom was originally limited to the elite of the Imperial Court, but soon spread to samurai society and, by the Edo period, to the common people as well. Tokugawa Yoshimune planted areas of cherry blossom trees to encourage this. Under the sakura trees, people had lunch and drank sake in cheerful feasts. </p>. 
        <div className="text-center">
        <img className="w-64 h-40 rounded-xl ml-4 mr-4 float-right" alt="main" src="https://resources.matcha-jp.com/resize/720x2000/2019/02/05-70586.jpeg"/>
        </div>
        <br/>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">Woodblock print of Mount Fuji and cherry blossom from Thirty-six Views of Mount Fuji by Hiroshige Every year the Japanese Meteorological Agency and the public track the sakura zensen (cherry blossom front) as it moves northward up the archipelago with the approach of warmer weather via nightly forecasts following the weather segment of news programs. The blossoming begins in Okinawa in January, and typically reaches Kyoto and Tokyo at the end of March or the beginning of April. It proceeds into areas at the higher altitudes and northward, arriving in Hokkaido a few weeks later. Japanese pay close attention to these forecasts and turn out in large numbers at parks, shrines and temples with family and friends to hold flower-viewing parties. Hanami festivals celebrate the beauty of the cherry blossom and for many are a chance to relax and enjoy the beautiful view. The custom of hanami dates back many centuries in Japan. The eighth-century chronicle Nihon Shoki (日本書紀) records hanami festivals being held as early as the third century AD.</p>
        <br/>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">Most Japanese schools and public buildings have cherry blossom trees outside of them. Since the fiscal and school year both begin in April, in many parts of Honshu, the first day of work or school coincides with the cherry blossom season.The Japan Cherry Blossom Association developed a list of Japan's Top 100 Cherry Blossom Spots (ja:日本さくら名所100選)[9] with at least one location in every prefecture."</p>  
        <br></br>
        <h2 className="text-left ml-20 mt-9 mb-4 font-serif text-xl text-pink-800 font-bold">Simbolism in Japan</h2>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">"In Japan, cherry blossoms symbolize clouds due to their nature of blooming en masse, besides being an enduring metaphor for the ephemeral nature of life, an aspect of Japanese cultural tradition that is often associated with Buddhist influence, and which is embodied in the concept of mono no aware. The association of the cherry blossom with mono no aware dates back to 18th-century scholar Motoori Norinaga. The transience of the blossoms, the exquisite beauty and volatility, has often been associated with mortality and graceful and readily acceptance of destiny and karma; for this reason, cherry blossoms are richly symbolic, and have been utilized often in Japanese art, manga, anime, and film, as well as at musical performances for ambient effect. There is at least one popular folk song, originally meant for the shakuhachi (bamboo flute), titled "Sakura", and several pop songs. The flower is also represented on all manner of consumer goods in Japan, including kimono, stationery, and dishware."</p>
        <br/>
        <div className="text-center">
        <img className="w-64 h-40 rounded-xl ml-4 mr-4 float-left" alt="main" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnSUlvY-l-Lhbc__RvBDwsJMbpG2_z68VuhQ&usqp=CAU"/>
        </div>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">"The Sakurakai or Cherry Blossom Society was the name chosen by young officers within the Imperial Japanese Army in September 1930 for their secret society established with the goal of reorganizing the state along totalitarian militaristic lines, via a military coup d'état if necessary.</p>
        <br/>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">During World War II, the cherry blossom was used to motivate the Japanese people, to stoke nationalism and militarism among the populace. Even prior to the war, they were used in propaganda to inspire "Japanese spirit", as in the "Song of Young Japan", exulting in "warriors" who were "ready like the myriad cherry blossoms to scatter". In 1932, Akiko Yosano's poetry urged Japanese soldiers to endure sufferings in China and compared the dead soldiers to cherry blossoms. Arguments that the plans for the Battle of Leyte Gulf, involving all Japanese ships, would expose Japan to serious danger if they failed, were countered with the plea that the Navy be permitted to "bloom as flowers of death". The last message of the forces on Peleliu was "Sakura, Sakura" — cherry blossoms. Japanese pilots would paint them on the sides of their planes before embarking on a suicide mission, or even take branches of the trees with them on their missions. A cherry blossom painted on the side of the bomber symbolized the intensity and ephemerality of life; in this way, the aesthetic association was altered such that falling cherry petals came to represent the sacrifice of youth in suicide missions to honor the emperor. The first kamikaze unit had a subunit called Yamazakura or wild cherry blossom. The government even encouraged the people to believe that the souls of downed warriors were reincarnated in the blossoms.In its colonial enterprises, imperial Japan often planted cherry trees as a means of "claiming occupied territory as Japanese space".</p>
        <br/>
        <p className="font-serif ml-5 mr-7 text-justify indent-3.5">"Cherry blossoms are a prevalent symbol in Irezumi, the traditional art of Japanese tattoos. In tattoo art, cherry blossoms are often combined with other classic Japanese symbols like koi fish, dragons or tigers. It was later used for the Tokyo 2020 Paralympics mascot Someity."</p>
        <br/>
        <hr className="mt-7"></hr>
       </div>
    )
}

export default TextMain